version: '3.8'

services:
        api-service:
                build:
                        context: ./backend
                        dockerfile: Dockerfile
                ports:
                        - 1337:80
                command: sh -c "python api.py"
                volumes:
                        -  ./backend:/app

        website:
                build:
                        context: ./frontend
                        dockerfile: Dockerfile
                ports:
                        - 3000:3000
                depends_on:
                        - api-service
                stdin_open: True 
                volumes:
                        - ./frontend:/app
                        - node_modules:/app/node_modules # Data volume for node_modules

volumes:
        node_modules:

